(ns gcp.pubsub.v1.clients.SubscriptionAdminClient
  (:require [gcp.global :as g])
  (:import [com.google.cloud.pubsub.v1 SubscriptionAdminClient]))

;create()
;create(SubscriptionAdminSettings settings)
;create(SubscriberStub stub)
;SubscriptionAdminClient(SubscriptionAdminSettings settings)
;SubscriptionAdminClient(SubscriberStub stub)
;acknowledge(AcknowledgeRequest request)
;acknowledge(ProjectSubscriptionName subscription, List<String> ackIds) (deprecated)
;acknowledge(SubscriptionName subscription, List<String> ackIds)
;acknowledge(String subscription, List<String> ackIds)
;acknowledgeCallable()
;awaitTermination(long duration, TimeUnit unit)
;close()
;createSnapshot(CreateSnapshotRequest request)
;createSnapshot(ProjectSnapshotName name, ProjectSubscriptionName subscription) (deprecated)
;createSnapshot(ProjectSnapshotName name, String subscription) (deprecated)
;createSnapshot(SnapshotName name, SubscriptionName subscription)
;createSnapshot(String name, ProjectSubscriptionName subscription) (deprecated)
;createSnapshot(String name, SubscriptionName subscription) (deprecated)
;createSnapshot(String name, String subscription)
;createSnapshotCallable()
;createSubscription(ProjectSubscriptionName name, ProjectTopicName topic, PushConfig pushConfig, int ackDeadlineSeconds) (deprecated)
;createSubscription(ProjectSubscriptionName name, TopicName topic, PushConfig pushConfig, int ackDeadlineSeconds) (deprecated)
;createSubscription(ProjectSubscriptionName name, String topic, PushConfig pushConfig, int ackDeadlineSeconds) (deprecated)
;createSubscription(Subscription request)
;createSubscription(SubscriptionName name, TopicName topic, PushConfig pushConfig, int ackDeadlineSeconds)
;createSubscription(SubscriptionName name, String topic, PushConfig pushConfig, int ackDeadlineSeconds)
;createSubscription(String name, TopicName topic, PushConfig pushConfig, int ackDeadlineSeconds)
;createSubscription(String name, String topic, PushConfig pushConfig, int ackDeadlineSeconds)
;createSubscriptionCallable()
;deleteSnapshot(DeleteSnapshotRequest request)
;deleteSnapshot(ProjectSnapshotName snapshot) (deprecated)
;deleteSnapshot(SnapshotName snapshot)
;deleteSnapshot(String snapshot)
;deleteSnapshotCallable()
;deleteSubscription(DeleteSubscriptionRequest request)
;deleteSubscription(ProjectSubscriptionName subscription) (deprecated)
;deleteSubscription(SubscriptionName subscription)
;deleteSubscription(String subscription)
;deleteSubscriptionCallable()
;getIamPolicy(GetIamPolicyRequest request)
;getIamPolicy(String resource) (deprecated)
;getIamPolicyCallable()
;getSettings()
;getSnapshot(GetSnapshotRequest request)
;getSnapshot(ProjectSnapshotName snapshot) (deprecated)
;getSnapshot(SnapshotName snapshot)
;getSnapshot(String snapshot)
;getSnapshotCallable()
;getStub()
;getSubscription(GetSubscriptionRequest request)
;getSubscription(ProjectSubscriptionName subscription) (deprecated)
;getSubscription(SubscriptionName subscription)
;getSubscription(String subscription)
;getSubscriptionCallable()
;isShutdown()
;isTerminated()
;listSnapshots(ListSnapshotsRequest request)
;listSnapshots(ProjectName project)
;listSnapshots(String project)
;listSnapshotsCallable()
;listSnapshotsPagedCallable()
;listSubscriptions(ListSubscriptionsRequest request)
;listSubscriptions(ProjectName project)
;listSubscriptions(String project)
;listSubscriptionsCallable()
;listSubscriptionsPagedCallable()
;modifyAckDeadline(ModifyAckDeadlineRequest request)
;modifyAckDeadline(SubscriptionName subscription, List<String> ackIds, int ackDeadlineSeconds)
;modifyAckDeadline(String subscription, List<String> ackIds, int ackDeadlineSeconds)
;modifyAckDeadlineCallable()
;modifyPushConfig(ModifyPushConfigRequest request)
;modifyPushConfig(ProjectSubscriptionName subscription, PushConfig pushConfig) (deprecated)
;modifyPushConfig(SubscriptionName subscription, PushConfig pushConfig)
;modifyPushConfig(String subscription, PushConfig pushConfig)
;modifyPushConfigCallable()
;pull(ProjectSubscriptionName subscription, int maxMessages) (deprecated)
;pull(PullRequest request)
;pull(SubscriptionName subscription, boolean returnImmediately, int maxMessages)
;pull(SubscriptionName subscription, int maxMessages)
;pull(String subscription, boolean returnImmediately, int maxMessages)
;pull(String subscription, int maxMessages)
;pullCallable()
;seek(SeekRequest request)
;seekCallable()
;setIamPolicy(SetIamPolicyRequest request)
;setIamPolicy(String resource, Policy policy) (deprecated)
;setIamPolicyCallable()
;shutdown()
;shutdownNow()
;streamingPullCallable()
;testIamPermissions(TestIamPermissionsRequest request)
;testIamPermissions(String resource, List<String> permissions) (deprecated)
;testIamPermissionsCallable()
;updateSnapshot(Snapshot snapshot, FieldMask updateMask)
;updateSnapshot(UpdateSnapshotRequest request)
;updateSnapshotCallable()
;updateSubscription(Subscription subscription, FieldMask updateMask)
;updateSubscription(UpdateSubscriptionRequest request)
;updateSubscriptionCallable()
