(ns gcp.vertexai.load-test
  (:require [gcp.vertexai.generativeai :as gen-ai]
            [gcp.protobuf]
            [clojure.stacktrace]
            [gcp.vertexai.v1.api.Attribution]
            [gcp.vertexai.v1.api.Blob]
            [gcp.vertexai.v1.api.BlurBaselineConfig]
            [gcp.vertexai.v1.api.CachedContent]
            [gcp.vertexai.v1.api.Candidate]
            [gcp.vertexai.v1.api.Citation]
            [gcp.vertexai.v1.api.CitationMetadata]
            [gcp.vertexai.v1.api.CodeExecutionResult]
            [gcp.vertexai.v1.api.ComputeTokensRequest]
            [gcp.vertexai.v1.api.ComputeTokensResponse]
            [gcp.vertexai.v1.api.Content]
            [gcp.vertexai.v1.api.CountTokensRequest]
            [gcp.vertexai.v1.api.CountTokensResponse]
            [gcp.vertexai.v1.api.DirectPredictRequest]
            [gcp.vertexai.v1.api.DirectPredictResponse]
            [gcp.vertexai.v1.api.DirectRawPredictRequest]
            [gcp.vertexai.v1.api.DirectRawPredictResponse]
            [gcp.vertexai.v1.api.EnterpriseWebSearch]
            [gcp.vertexai.v1.api.ExecutableCode]
            [gcp.vertexai.v1.api.ExplainRequest]
            [gcp.vertexai.v1.api.ExplainResponse]
            [gcp.vertexai.v1.api.Explanation]
            [gcp.vertexai.v1.api.ExplanationMetadataOverride]
            [gcp.vertexai.v1.api.ExplanationParameters]
            [gcp.vertexai.v1.api.ExplanationSpecOverride]
            [gcp.vertexai.v1.api.FeatureNoiseSigma]
            [gcp.vertexai.v1.api.FileData]
            [gcp.vertexai.v1.api.FunctionCall]
            [gcp.vertexai.v1.api.FunctionCallingConfig]
            [gcp.vertexai.v1.api.FunctionDeclaration]
            [gcp.vertexai.v1.api.FunctionResponse]
            [gcp.vertexai.v1.api.GenerateContentRequest]
            [gcp.vertexai.v1.api.GenerateContentResponse]
            [gcp.vertexai.v1.api.GenerationConfig]
            [gcp.vertexai.v1.api.GoogleSearchRetrieval]
            [gcp.vertexai.v1.api.GroundingChunk]
            [gcp.vertexai.v1.api.GroundingMetadata]
            [gcp.vertexai.v1.api.GroundingSupport]
            [gcp.vertexai.v1.api.HarmCategory]
            [gcp.vertexai.v1.api.IntegratedGradientsAttribution]
            [gcp.vertexai.v1.api.ModelExplanation]
            [gcp.vertexai.v1.api.Neighbor]
            [gcp.vertexai.v1.api.Part]
            [gcp.vertexai.v1.api.PredictRequest]
            [gcp.vertexai.v1.api.PredictResponse]
            [gcp.vertexai.v1.api.RagRetrievalConfig]
            [gcp.vertexai.v1.api.RawPredictRequest]
            [gcp.vertexai.v1.api.Retrieval]
            [gcp.vertexai.v1.api.RetrievalMetadata]
            [gcp.vertexai.v1.api.SafetyRating]
            [gcp.vertexai.v1.api.SafetySetting]
            [gcp.vertexai.v1.api.SampledShapleyAttribution]
            [gcp.vertexai.v1.api.Schema]
            [gcp.vertexai.v1.api.SearchEntryPoint]
            [gcp.vertexai.v1.api.Segment]
            [gcp.vertexai.v1.api.SmoothGradConfig]
            [gcp.vertexai.v1.api.StreamDirectPredictRequest]
            [gcp.vertexai.v1.api.StreamDirectPredictResponse]
            [gcp.vertexai.v1.api.StreamDirectRawPredictRequest]
            [gcp.vertexai.v1.api.StreamDirectRawPredictResponse]
            [gcp.vertexai.v1.api.StreamingPredictRequest]
            [gcp.vertexai.v1.api.StreamingPredictResponse]
            [gcp.vertexai.v1.api.StreamingRawPredictRequest]
            [gcp.vertexai.v1.api.StreamingRawPredictResponse]
            [gcp.vertexai.v1.api.Tensor]
            [gcp.vertexai.v1.api.TokensInfo]
            [gcp.vertexai.v1.api.Tool]
            [gcp.vertexai.v1.api.ToolConfig]
            [gcp.vertexai.v1.api.Type]
            [gcp.vertexai.v1.api.VertexAISearch]
            [gcp.vertexai.v1.api.VertexRagStore]
            [gcp.vertexai.v1.api.VideoMetadata]
            [gcp.vertexai.v1.api.XraiAttribution]))

(println "All API schemas loaded.")

(try
  (println "Attempting gen-ai/as-request...")
  (let [req (gen-ai/as-request {:model :gemini-2.5-flash} ["hello!"])]
    (println "Request formed successfully:")
    (clojure.pprint/pprint req))
  (catch Exception e
    (println "Caught exception:" (.getMessage e))
    (when-let [data (ex-data e)]
      (clojure.pprint/pprint data))
    (clojure.stacktrace/print-stack-trace e)))