;; THIS FILE IS GENERATED; DO NOT EDIT
(ns gcp.vertexai.api.ExecutableCode
  {:doc
     "<pre>\nCode generated by the model that is meant to be executed, and the result\nreturned to the model.\n\nGenerated when using the [FunctionDeclaration] tool and\n[FunctionCallingConfig] mode is set to [Mode.CODE].\n</pre>\n\nProtobuf type {@code google.cloud.vertexai.v1.ExecutableCode}"
   :file-git-sha "d937fcec0c42304b32ec37bc46cfb9739b978382"
   :fqcn "com.google.cloud.vertexai.api.ExecutableCode"
   :gcp.dev/certification
     {:base-seed 1775465653448
      :manifest "2e809e6a-933c-51dd-8bb9-567961e7a29e"
      :passed-stages
        {:smoke 1775465653448 :standard 1775465653449 :stress 1775465653450}
      :protocol-hash
        "4c8153e592bbd21aa5ceea5ac76bb3400f5daf613bb57ad03e7e373f401ca3ad"
      :timestamp "2026-04-06T08:54:14.629739139Z"}}
  (:require [gcp.global :as global])
  (:import [com.google.cloud.vertexai.api ExecutableCode ExecutableCode$Builder
            ExecutableCode$Language]))

(declare from-edn to-edn Language-from-edn Language-to-edn)

(def Language-schema
  [:enum
   {:closed true,
    :doc
      "<pre>\nSupported programming languages for the generated code.\n</pre>\n\nProtobuf enum {@code google.cloud.vertexai.v1.ExecutableCode.Language}",
    :gcp/category :nested/enum,
    :gcp/key :gcp.vertexai.api/ExecutableCode.Language} "LANGUAGE_UNSPECIFIED"
   "PYTHON"])

(defn ^ExecutableCode from-edn
  [arg]
  (global/strict! :gcp.vertexai.api/ExecutableCode arg)
  (let [builder (ExecutableCode/newBuilder)]
    (when (some? (get arg :code)) (.setCode builder (get arg :code)))
    (when (some? (get arg :language))
      (.setLanguage builder
                    (ExecutableCode$Language/valueOf (get arg :language))))
    (.build builder)))

(defn to-edn
  [^ExecutableCode arg]
  {:post [(global/strict! :gcp.vertexai.api/ExecutableCode %)]}
  (when arg
    (cond-> {:code (.getCode arg), :language (.name (.getLanguage arg))})))

(def schema
  [:map
   {:closed true,
    :doc
      "<pre>\nCode generated by the model that is meant to be executed, and the result\nreturned to the model.\n\nGenerated when using the [FunctionDeclaration] tool and\n[FunctionCallingConfig] mode is set to [Mode.CODE].\n</pre>\n\nProtobuf type {@code google.cloud.vertexai.v1.ExecutableCode}",
    :gcp/category :protobuf-message,
    :gcp/key :gcp.vertexai.api/ExecutableCode}
   [:code
    {:getter-doc
       "<pre>\nRequired. The code to be executed.\n</pre>\n\n<code>string code = 2 [(.google.api.field_behavior) = REQUIRED];</code>\n\n@return The code.",
     :setter-doc
       "<pre>\nRequired. The code to be executed.\n</pre>\n\n<code>string code = 2 [(.google.api.field_behavior) = REQUIRED];</code>\n\n@param value The code to set.\n@return This builder for chaining."}
    [:string {:min 1}]]
   [:language
    {:getter-doc
       "<pre>\nRequired. Programming language of the `code`.\n</pre>\n\n<code>\n.google.cloud.vertexai.v1.ExecutableCode.Language language = 1 [(.google.api.field_behavior) = REQUIRED];\n</code>\n\n@return The language.",
     :setter-doc
       "<pre>\nRequired. Programming language of the `code`.\n</pre>\n\n<code>\n.google.cloud.vertexai.v1.ExecutableCode.Language language = 1 [(.google.api.field_behavior) = REQUIRED];\n</code>\n\n@param value The language to set.\n@return This builder for chaining."}
    [:enum {:closed true} "LANGUAGE_UNSPECIFIED" "PYTHON"]]])

(global/include-schema-registry!
  (with-meta {:gcp.vertexai.api/ExecutableCode schema,
              :gcp.vertexai.api/ExecutableCode.Language Language-schema}
    {:gcp.global/name "gcp.vertexai.api.ExecutableCode"}))