;; THIS FILE IS GENERATED; DO NOT EDIT
(ns gcp.vertexai.api.GroundingMetadata
  {:doc
     "<pre>\nMetadata returned to client when grounding is enabled.\n</pre>\n\nProtobuf type {@code google.cloud.vertexai.v1.GroundingMetadata}"
   :file-git-sha "d937fcec0c42304b32ec37bc46cfb9739b978382"
   :fqcn "com.google.cloud.vertexai.api.GroundingMetadata"
   :gcp.dev/certification
     {:base-seed 1776627524442
      :manifest "2e809e6a-933c-51dd-8bb9-567961e7a29e"
      :passed-stages
        {:smoke 1776627524442 :standard 1776627524443 :stress 1776627524444}
      :protocol-hash
        "75d3372fb35f1e40bc5550be4e402bfd0b7a7edb8010ca96440bb4161b829c72"
      :timestamp "2026-04-19T19:38:45.892656656Z"}}
  (:require [gcp.foreign.com.google.protobuf :as protobuf]
            [gcp.global :as global]
            [gcp.vertexai.api.GroundingChunk :as GroundingChunk]
            [gcp.vertexai.api.GroundingSupport :as GroundingSupport]
            [gcp.vertexai.api.RetrievalMetadata :as RetrievalMetadata]
            [gcp.vertexai.api.SearchEntryPoint :as SearchEntryPoint])
  (:import [com.google.cloud.vertexai.api GroundingMetadata
            GroundingMetadata$Builder GroundingMetadata$SourceFlaggingUri
            GroundingMetadata$SourceFlaggingUri$Builder]
           [com.google.protobuf ProtocolStringList]))

(declare from-edn to-edn SourceFlaggingUri-from-edn SourceFlaggingUri-to-edn)

(defn ^GroundingMetadata$SourceFlaggingUri SourceFlaggingUri-from-edn
  [arg]
  (let [builder (GroundingMetadata$SourceFlaggingUri/newBuilder)]
    (when (some? (get arg :flagContentUri))
      (.setFlagContentUri builder (get arg :flagContentUri)))
    (when (some? (get arg :sourceId))
      (.setSourceId builder (get arg :sourceId)))
    (.build builder)))

(defn SourceFlaggingUri-to-edn
  [^GroundingMetadata$SourceFlaggingUri arg]
  (when arg
    (cond-> {}
      (some->> (.getFlagContentUri arg)
               (not= ""))
        (assoc :flagContentUri (.getFlagContentUri arg))
      (some->> (.getSourceId arg)
               (not= ""))
        (assoc :sourceId (.getSourceId arg)))))

(def SourceFlaggingUri-schema
  [:map
   {:closed true,
    :doc
      "<pre>\nSource content flagging uri for a place or review. This is currently\npopulated only for Google Maps grounding.\n</pre>\n\nProtobuf type {@code google.cloud.vertexai.v1.GroundingMetadata.SourceFlaggingUri}",
    :gcp/category :nested/protobuf-message,
    :gcp/key :gcp.vertexai.api/GroundingMetadata.SourceFlaggingUri}
   [:flagContentUri
    {:optional true,
     :getter-doc
       "<pre>\nA link where users can flag a problem with the source (place or review).\n(-- The link is generated by Google and it does not contain\ninformation from the user query. It may contain information of the\ncontent it is flagging, which can be used to identify places. --)\n</pre>\n\n<code>string flag_content_uri = 2;</code>\n\n@return The flagContentUri.",
     :setter-doc
       "<pre>\nA link where users can flag a problem with the source (place or review).\n(-- The link is generated by Google and it does not contain\ninformation from the user query. It may contain information of the\ncontent it is flagging, which can be used to identify places. --)\n</pre>\n\n<code>string flag_content_uri = 2;</code>\n\n@param value The flagContentUri to set.\n@return This builder for chaining."}
    [:string {:min 1, :gen/max 1}]]
   [:sourceId
    {:optional true,
     :getter-doc
       "<pre>\nId of the place or review.\n</pre>\n\n<code>string source_id = 1;</code>\n\n@return The sourceId.",
     :setter-doc
       "<pre>\nId of the place or review.\n</pre>\n\n<code>string source_id = 1;</code>\n\n@param value The sourceId to set.\n@return This builder for chaining."}
    [:string {:min 1, :gen/max 1}]]])

(defn ^GroundingMetadata from-edn
  [arg]
  (global/strict! :gcp.vertexai.api/GroundingMetadata arg)
  (let [builder (GroundingMetadata/newBuilder)]
    (when (some? (get arg :googleMapsWidgetContextToken))
      (.setGoogleMapsWidgetContextToken builder
                                        (get arg
                                             :googleMapsWidgetContextToken)))
    (when (seq (get arg :groundingChunks))
      (.addAllGroundingChunks builder
                              (mapv GroundingChunk/from-edn
                                (get arg :groundingChunks))))
    (when (seq (get arg :groundingSupports))
      (.addAllGroundingSupports builder
                                (mapv GroundingSupport/from-edn
                                  (get arg :groundingSupports))))
    (when (some? (get arg :retrievalMetadata))
      (.setRetrievalMetadata builder
                             (RetrievalMetadata/from-edn
                               (get arg :retrievalMetadata))))
    (when (some? (get arg :searchEntryPoint))
      (.setSearchEntryPoint builder
                            (SearchEntryPoint/from-edn
                              (get arg :searchEntryPoint))))
    (when (seq (get arg :sourceFlaggingUris))
      (.addAllSourceFlaggingUris builder
                                 (mapv SourceFlaggingUri-from-edn
                                   (get arg :sourceFlaggingUris))))
    (when (seq (get arg :webSearchQueries))
      (.addAllWebSearchQueries builder (seq (get arg :webSearchQueries))))
    (.build builder)))

(defn to-edn
  [^GroundingMetadata arg]
  {:post [(global/strict! :gcp.vertexai.api/GroundingMetadata %)]}
  (when arg
    (cond-> {}
      (.hasGoogleMapsWidgetContextToken arg)
        (assoc :googleMapsWidgetContextToken
          (.getGoogleMapsWidgetContextToken arg))
      (seq (.getGroundingChunksList arg)) (assoc :groundingChunks
                                            (mapv GroundingChunk/to-edn
                                              (.getGroundingChunksList arg)))
      (seq (.getGroundingSupportsList arg))
        (assoc :groundingSupports
          (mapv GroundingSupport/to-edn (.getGroundingSupportsList arg)))
      (.hasRetrievalMetadata arg) (assoc :retrievalMetadata
                                    (RetrievalMetadata/to-edn
                                      (.getRetrievalMetadata arg)))
      (.hasSearchEntryPoint arg) (assoc :searchEntryPoint
                                   (SearchEntryPoint/to-edn
                                     (.getSearchEntryPoint arg)))
      (seq (.getSourceFlaggingUrisList arg))
        (assoc :sourceFlaggingUris
          (mapv SourceFlaggingUri-to-edn (.getSourceFlaggingUrisList arg)))
      (seq (.getWebSearchQueriesList arg)) (assoc :webSearchQueries
                                             (protobuf/ProtocolStringList-to-edn
                                               (.getWebSearchQueriesList
                                                 arg))))))

(def schema
  [:map
   {:closed true,
    :doc
      "<pre>\nMetadata returned to client when grounding is enabled.\n</pre>\n\nProtobuf type {@code google.cloud.vertexai.v1.GroundingMetadata}",
    :gcp/category :protobuf-message,
    :gcp/key :gcp.vertexai.api/GroundingMetadata}
   [:googleMapsWidgetContextToken
    {:optional true,
     :read-only true,
     :getter-doc
       "<pre>\nOptional. Output only. Resource name of the Google Maps widget context\ntoken to be used with the PlacesContextElement widget to render contextual\ndata. This is populated only for Google Maps grounding.\n</pre>\n\n<code>\noptional string google_maps_widget_context_token = 8 [(.google.api.field_behavior) = OPTIONAL, (.google.api.field_behavior) = OUTPUT_ONLY];\n</code>\n\n@return The googleMapsWidgetContextToken."}
    [:string {:min 1, :gen/max 1}]]
   [:groundingChunks
    {:optional true,
     :getter-doc
       "<pre>\nList of supporting references retrieved from specified grounding source.\n</pre>\n\n<code>repeated .google.cloud.vertexai.v1.GroundingChunk grounding_chunks = 5;</code>",
     :setter-doc
       "<pre>\nList of supporting references retrieved from specified grounding source.\n</pre>\n\n<code>repeated .google.cloud.vertexai.v1.GroundingChunk grounding_chunks = 5;</code>"}
    [:sequential {:min 1, :gen/max 2} :gcp.vertexai.api/GroundingChunk]]
   [:groundingSupports
    {:optional true,
     :getter-doc
       "<pre>\nOptional. List of grounding support.\n</pre>\n\n<code>\nrepeated .google.cloud.vertexai.v1.GroundingSupport grounding_supports = 6 [(.google.api.field_behavior) = OPTIONAL];\n</code>",
     :setter-doc
       "<pre>\nOptional. List of grounding support.\n</pre>\n\n<code>\nrepeated .google.cloud.vertexai.v1.GroundingSupport grounding_supports = 6 [(.google.api.field_behavior) = OPTIONAL];\n</code>"}
    [:sequential {:min 1, :gen/max 2} :gcp.vertexai.api/GroundingSupport]]
   [:retrievalMetadata
    {:optional true,
     :read-only true,
     :getter-doc
       "<pre>\nOptional. Output only. Retrieval metadata.\n</pre>\n\n<code>\noptional .google.cloud.vertexai.v1.RetrievalMetadata retrieval_metadata = 7 [(.google.api.field_behavior) = OPTIONAL, (.google.api.field_behavior) = OUTPUT_ONLY];\n</code>\n\n@return The retrievalMetadata."}
    :gcp.vertexai.api/RetrievalMetadata]
   [:searchEntryPoint
    {:optional true,
     :getter-doc
       "<pre>\nOptional. Google search entry for the following-up web searches.\n</pre>\n\n<code>\noptional .google.cloud.vertexai.v1.SearchEntryPoint search_entry_point = 4 [(.google.api.field_behavior) = OPTIONAL];\n</code>\n\n@return The searchEntryPoint.",
     :setter-doc
       "<pre>\nOptional. Google search entry for the following-up web searches.\n</pre>\n\n<code>\noptional .google.cloud.vertexai.v1.SearchEntryPoint search_entry_point = 4 [(.google.api.field_behavior) = OPTIONAL];\n</code>"}
    :gcp.vertexai.api/SearchEntryPoint]
   [:sourceFlaggingUris
    {:optional true,
     :getter-doc
       "<pre>\nList of source flagging uris. This is currently populated only for Google\nMaps grounding.\n</pre>\n\n<code>\nrepeated .google.cloud.vertexai.v1.GroundingMetadata.SourceFlaggingUri source_flagging_uris = 9;\n</code>",
     :setter-doc
       "<pre>\nList of source flagging uris. This is currently populated only for Google\nMaps grounding.\n</pre>\n\n<code>\nrepeated .google.cloud.vertexai.v1.GroundingMetadata.SourceFlaggingUri source_flagging_uris = 9;\n</code>"}
    [:sequential {:min 1, :gen/max 2}
     [:ref :gcp.vertexai.api/GroundingMetadata.SourceFlaggingUri]]]
   [:webSearchQueries
    {:optional true,
     :getter-doc
       "<pre>\nOptional. Web search queries for the following-up web search.\n</pre>\n\n<code>repeated string web_search_queries = 1 [(.google.api.field_behavior) = OPTIONAL];</code>\n\n@return A list containing the webSearchQueries.",
     :setter-doc
       "<pre>\nOptional. Web search queries for the following-up web search.\n</pre>\n\n<code>repeated string web_search_queries = 1 [(.google.api.field_behavior) = OPTIONAL];\n</code>\n\n@param values The webSearchQueries to add.\n@return This builder for chaining."}
    :gcp.foreign.com.google.protobuf/ProtocolStringList]])

(global/include-schema-registry!
  (with-meta {:gcp.vertexai.api/GroundingMetadata schema,
              :gcp.vertexai.api/GroundingMetadata.SourceFlaggingUri
                SourceFlaggingUri-schema}
    {:gcp.global/name "gcp.vertexai.api.GroundingMetadata"}))